name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build Wii example
    strategy:
      matrix:
        zig: ["0.13.0"]
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
 
    steps:
    - uses: actions/checkout@v4

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: ${{matrix.zig}}

    - name: Build hello-world example
      run: zig build --verbose
      working-directory: examples/hello-world

    - name: Build sdl-app example
      run: zig build --verbose
      working-directory: examples/sdl-app
