name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build Wii example
    runs-on: ubuntu-latest
    #container: devkitpro/devkitppc:latest
 
    steps:
    - uses: actions/checkout@v4

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v1
      with:
        version: "0.13.0"

    - name: Build hello-world example
      run: zig build
      working-directory: examples/hello-world

    - name: Build sdl-app example
      run: zig build
      working-directory: examples/sdl-app
